# This is a basic workflow to help you get started with Actions

name: Update Website

# Controls when the action will run.
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Set Node version
      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: 15.x
      # Install package dependencies
      - name: Install dependencies
        run: yarn install --prod --pure-lockfile
      # Build the site
      - name: Build
        run: yarn run build
      # Sync the public folder to the server
      - name: Sync to Deploy
        env:
          dest: ${{ secrets.server_path }}
        run: |
          echo "${{secrets.deploy_key}}" > deploy_key
          chmod 600 ./deploy_key
          rsync -chav --delete \
            -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' \
            --exclude /deploy_key \
            --exclude /.git/ \
            --exclude /.github/ \
            --exclude /node_modules/ \
            ./public/* ${{env.dest}}
